/*
 * this example demonstrate how to trigger an envelope with a trigger signal generated by an oscillator.
 */

#include "Klangstrom.h"
#include "KlangNodes.hpp"

using namespace klang;
using namespace klangstrom;

NodeVCOWavetable mTriggerRampFrequency;
NodeEnvelope     mEnvelopeFreq;
NodeADSR         mADSR;
NodeVCOWavetable mOsc;
NodeDAC          mDAC;

void setup() {
    Klang::connect(mTriggerRampFrequency, Node::CH_OUT_SIGNAL, mEnvelopeFreq, NodeEnvelope::CH_IN_TRIGGER);
    Klang::connect(mEnvelopeFreq, Node::CH_OUT_SIGNAL, mOsc, NodeVCOWavetable::CH_IN_FREQ);
    Klang::connect(mADSR, Node::CH_OUT_SIGNAL, mOsc, NodeVCOWavetable::CH_IN_AMP);
    Klang::connect(mOsc, Node::CH_OUT_SIGNAL, mDAC, NodeDAC::CH_IN_SIGNAL);

    mEnvelopeFreq.set_start_value(1.0);
    mEnvelopeFreq.add_stage(0.025, 2.0);
    mEnvelopeFreq.add_stage(0.05, 16.0);
    mEnvelopeFreq.add_stage(0.025, 8.0);
    mEnvelopeFreq.set_value_scale(27.5);

    mTriggerRampFrequency.set_waveform(NodeVCOWavetable::WAVEFORM::SAWTOOTH);
    mTriggerRampFrequency.set_frequency(2);

    mOsc.set_waveform(NodeVCOWavetable::WAVEFORM::SAWTOOTH);
    mOsc.set_frequency(55);
    mOsc.set_amplitude(0.33);
}

void loop() {}

void audioblock(float** input_signal, float** output_signal) {
    mDAC.process_frame(output_signal[LEFT], output_signal[RIGHT]);
}

void event_receive(const EVENT_TYPE event, const void* data) {
    switch (event) {
        case EVENT_MOUSE_PRESSED:
        case EVENT_ENCODER_BUTTON_PRESSED:
            mADSR.start();
            break;
        case EVENT_MOUSE_RELEASED:
        case EVENT_ENCODER_BUTTON_RELEASED:
            mADSR.stop();
            break;
        case EVENT_MOUSE_MOVED:
        case EVENT_MOUSE_DRAGGED:
            mTriggerRampFrequency.set_frequency(mouse_event(data).x * 12);
            mEnvelopeFreq.set_time_scale(mouse_event(data).y * 2);
            break;
    }
}
